name: "Cache NixOS configurations"
on:
  push:
    branches:
      - "main"
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: mycache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: "nix build .#nixosConfigurations.chlap.config.system.build.toplevel"
    - run: "nix build .#nixosConfigurations.nixbox.config.system.build.toplevel"
